# Generated by Django 6.0.3 on 2026-04-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='user',
            new_name='creator',
        ),
    ]
